services:
    app:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        container_name: crm-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - '.:/var/www/html'
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
        # network_mode: host
        # image: 'sail-8.4/app'
        # extra_hosts:
        #     - 'host.docker.internal:host-gateway'
        # ports:
        #     - '${APP_PORT:-80}:80'
        #     - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'

        # networks:
        #     - sail

    nginx:
        image: nginx:alpine
        container_name: crm-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx:/etc/nginx/conf.d
        depends_on:
            - app

    mysql:
        image: 'mysql:8.0'
        container_name: crm-mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: crm
            MYSQL_USER: sail
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - mysqldata:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password

    node:
        image: node:20
        container_name: crm-node
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        environment:
            - NODE_ENV=development
        command: [ "npm", "run", "dev" ]

volumes:
    mysqldata:


